### ISSUE TITLE
Unable to write file at location

### ISSUE THREAD

**Issue by sovetski** [softavis/flysystem-cloudflare#3]
Hi,

I have this error when I try to upload an image:

`Unable to write file at location: 56afa13f8f49c96f1c2245fbed14c17a0526f05d.png. getimagesizefromstring(): Argument #1 ($string) must be of type string, resource given`

I created a pull request: https://github.com/softavis/flysystem-cloudflare/pull/4

**Comment by naskoff** [comment]
Hi @sovetski , if you want to upload resource file type, use writeStream() method. Symfony HttpClient works with both.

**Comment by sovetski** [comment]
> Hi @sovetski , if you want to upload resource file type, use writeStream() method. Symfony HttpClient works with both.

Hi, I am using `league/flysystem-bundle` and `vich/uploader-bundle` so it decides which method to use, and I debugged it, it is writeStream() which is used. With my pull request it resolves the problem, but now it returns

Unable to write file at location: 85fd6fc806a5660717c5599bdeba72ee2bce7568.png. HTTP/2 400 returned for "https://api.cloudflare.com/client/v4/accounts/HIDDENACCOUNTID/images/v1".

Without my PR:
![image](https://github.com/softavis/flysystem-cloudflare/assets/13520683/9b61a973-183e-4d41-9808-b26fa91688b1)

**Comment by naskoff** [comment]
> Unable to write file at location: 85fd6fc806a5660717c5599bdeba72ee2bce7568.png. HTTP/2 400 returned for "https://api.cloudflare.com/client/v4/accounts/HIDDENACCOUNTID/images/v1".
>

If you already have an image with this ID (85fd6fc806a5660717c5599bdeba72ee2bce7568.png), cloudflare does not accept multiple images with same ID.

**Comment by sovetski** [comment]
> > Unable to write file at location: 85fd6fc806a5660717c5599bdeba72ee2bce7568.png. HTTP/2 400 returned for "https://api.cloudflare.com/client/v4/accounts/HIDDENACCOUNTID/images/v1".
> 
> If you already have an image with this ID (85fd6fc806a5660717c5599bdeba72ee2bce7568.png), cloudflare does not accept multiple images with same ID.

No I have 0 images in Cloudflare 😕

**Comment by naskoff** [comment]
Hi @sovetski , the problem with the upload stream resource is the upload method on the client. Can not get image width & height from resource and so on. I fixed it with the latest release 0.1.1.
Can you try it as follow configuration from readme?

**Comment by sovetski** [comment]
@naskoff thank you for your effort, really appreciated!!

I followed the README configuration, with the version 0.1.1 I don't have any more the error `must be of type string, resource given`

But this error still there `Unable to write file at location: e0043b759e663c0d936d7e42c705ddb495c8702e.png. HTTP/2 400  returned for "https://api.cloudflare.com/client/v4/accounts/HIDDEN/images/v1`

It is very strange, in Client.php, when I dump `$formData` from `upload` method, it returns `jpg` mime type/extension, but my uploaded image is `png`. File width/height are ok

![image](https://github.com/softavis/flysystem-cloudflare/assets/13520683/c79b54b0-c291-40bb-9b33-3f2ddd73bea3)

**Comment by naskoff** [comment]
Ahh, this error 400 returned from Cloudflare - your API key does not have proper permissions - Cloudflare Images (there is a template for that). 

![image](https://github.com/softavis/flysystem-cloudflare/assets/5497493/89de16b9-040a-498a-87bb-45ef911949a2)

For your last lines, is totally strange - exceptions throw png filename, debug info have .jpg filename?

**Comment by sovetski** [comment]
@naskoff man, thank you very much!!!! you saved my day!! If you can add your Sponsor link on the repository, it will be a pleasure  to participate. Even if the amount will not be huge, other people like me will be able to support you, I respect all the people who participate in open source.

Regarding the issue with file name, I am looking for it, If I find the issue I will comment here

**Comment by naskoff** [comment]
Thanks, I can add you as a contributor if you wish. Sponsor links are too much for this library.

Anyway, you can be the first to donate via [BuyMeACoffee](https://www.buymeacoffee.com/hristoff)

**Comment by sovetski** [comment]
The extension problem was coming from my custom code, all is ok now, thank you again!
